server:
  port: 8080
  servlet:
    context-path:
    encoding:
      charset: UTF-8

spring:
  mvc:
#    static-path-pattern: /static/** #이거 해제 하고 stomp.js파일 접근됨
    path match:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: file:media, classpath:/static

  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#  rabbitmq:
#    host: localhost # rabbitMQ host (docker로 띄웠음)
#    port: 5672 # default port
#    username: guest # default username
#    password: guest # default password

jwt:
  secret: ${JWT_SECRET}
  accessExpirationTime: ${JWT_EXPIRATION}
